# TODO
# Chat Clearing Command
# Chat Muting Command
# Chat Cooldown
# Broadcast Command
# Automatic Messages with sound support
# Anti-Raid

# Section Permissions:
# 'pcm.chatformatting.colors' - Use colors in chat (&a)
# 'pcm.chatformatting.hex' - Use hex colors in chat (&#00FF00)
# 'pcm.chatformatting.magic' - Use magic formats in chat (&k)
chat-formatting:
  enabled: true

  # Available Placeholder List (PlaceholderAPI Supported)
  # {message} - The message
  # {username} - Player's name
  # {displayname} - Player's display name
  # {prefix} - The player's vault/luckperms prefix (or nothing if none installed)
  # {suffix} - the player's vault/luckperms suffix (or nothing if none installed)
  chat-format: "{prefix}&7{username}: &f{message}"

  # Per-Group chat format (Requires Vault or LuckPerms)
  group-formats:
  #  default: "&8[Default] &7{username}: &f{message}"
  #  owner: "&4[Owner] &7{username}: &f{message}"


# Section permissions:
# 'pcm.chatfilter.bypass' - Bypass the chat filter
# 'pcm.chatfilter.notify' - Receive notifications when someone uses a filtered word
chat-filter:
  enabled: true

  # Lists of letters that can be substituted for each other
  # For example 'e' can be substitutted with '3' like in: h3llo
  alike-pairs:
    - "il|;:\\\\/1"
    - "@a4"
    - " .,"
    - "0o"
    - "7t"
    - "5s"
    - "3e"
    - "qg"

  # List of words that should be filtered
  filtered-words:
    - "nigger"
    - "fuck"
    - "shit"
    - "kys"
    - "kill yourself"
    - "retard"

  # The removal strategy for filtered words
  # 'cancel_message' - Completely prevents messages with filtered words from being sent
  # 'replace_filtered' - Replaces filtered words with the 'replacement-character'
  # NOTE: If an invalid removal strategy is provided 'cancel_message' will be used
  removal-strategy: cancel_message

  # Explained in the dscription for 'removal-strategy'
  # If more than one character is provided only the first will be used
  replacement-character: "*"

  # Commands that should be sent when a player uses a filtered word
  punish-commands:
  # - "/mute {player} 1h Using bad words"

  # Should staff be notified when a player uses a filtered word
  notify-staff: true

  # The format for staff notifications
  # PlaceholderAPI is supported from the point of view of the offending player
  # {player} - The player who sent the message
  # {message} - The unfiltered message
  notify-staff-format: "&4[FILTER] &c{player} &7-> &c{message}"


# Section Permissions
# 'pcm.commands.toggleabc' - Command that toggles automatic broadcasts per-player
# 'pcm.commands.nextabc' - Command that forces the next automatic broadcast to occur (for debugging purposes)
automatic-broadcast:
  enabled: false

  # How often automatic messages will be sent to players (in seconds)
  message-frequency: 60

  # How the messages that will be sent to each player should be picked
  # 'random' - A random message will be picked and sent to all players
  # 'random_per_player' - A different random message will be picked for each player
  # 'sequence' - Each message will be sent one after another in a loop
  mode: sequence

  messages:
    # A unique message identifier (doesn't really matter it's here so the config can look nicer)
    discord:
      # What sound to play when this message is sent, set to 'none' to disable
      # List of all sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
      sound: block_note_block_pling

      # The volume and pitch that should be used when playing the sound
      # Ignored if 'sound' is 'none'
      sound-volume: 1
      sound-pitch: 1

      # The lines of the message that should actually be sent
      messages:
        - "&5Did you know we have a server discord?"
        - "&dYou can join it at https://discord.gg/example"

    store:
      sound: block_note_block_pling
      sound-volume: 1
      sound-pitch: 1
      messages:
        - "&5Want a slight advantage against others?"
        - "&dCheck out our store at https://store.example.net"

# Section permissions:
# 'pcm.commands.chatclear' - Command used to clear the chat
# 'pcm.commands.broadcast' - Command that broadcasts a message to all online players
commands:
  # {player} - The player who cleared the chat
  chat-clear-messages:
    - ""
    - "&7The chat has been cleared by &c{player}"
    - ""

  # {player} - The player who muted the chat
  # {state} - Either 'muted' or 'unmuted' depending on what happened
  mute-chat-messages:
    - ""
    - "&7The chat has been {state} by &c{player}"
    - ""

  # {message} - The message that has been broadcast
  broadcast-messages:
    - "&c&lBROADCAST &7| &f{message}"


# <!> DO NOT TOUCH <!>
# Used for automatically adding new config values in newer versions of the plugin
config-version: ${version}