name: PyrsChatManager
version: ${version}
authors: [Pyr#6969]
softdepend: [Vault, LuckPerms, PlaceholderAPI]
main: lol.pyr.chatmanager.ChatPlugin
api-version: 1.13

commands:
  clearchat:
    aliases: [chatclear]
    permission: pcm.commands.clearchat
  mutechat:
    aliases: [chatmute]
    permission: pcm.commands.mutechat
  pcmreload:
    permission: pcm.commands.pcmreload
  broadcast:
    aliases: [bc]
    permission: pcm.commands.broadcast